### ISSUE TITLE
非常不错的项目，有个问题请教一下

### ISSUE THREAD

**Issue by xgy560501** [LianGee/galio#24]
@classmethod
    def deploy(cls, user, project_id, image_name):
        project = Project.select().get(project_id)
        deploy_log = DeployLog(
            project_name=project.name,
            project_id=project_id,
            image_name=image_name,
            user_name=user.name,
            status=DeployStatus.INIT,
            uuid=uuid.uuid4().hex
        )

这里的user.name哪来的

**Comment by LianGee** [comment]
参考这里 `https://github.com/LianGee/galio/blob/f1e7e1944e53be09ee91252f73e6c572b5f07121/common/login.py`
登录之后用户信息存在g.user中

**Comment by xgy560501** [comment]
ok  感谢 顺便问一下  template里面content字段能给个demo看下吗

**Comment by LianGee** [comment]
[参考这里](https://github.com/LianGee/galio/blob/master/docs/img/template.jpg)

**Comment by xgy560501** [comment]
非常感谢  我把login模块屏蔽了 项目已经跑起来  前端代码有吗可以给参考一下吗

**Comment by LianGee** [comment]
https://github.com/LianGee/galio-fe

**Comment by xgy560501** [comment]
您的harbor版本是1.*版本的吗，我这边harbor是2.0版本的加了token认证，难处理

**Comment by Ilovedocker** [comment]
前端项目里面是不是少了一个build？

**Comment by LianGee** [comment]
> 您的harbor版本是1.*版本的吗，我这边harbor是2.0版本的加了token认证，难处理

推送harbor用的docker的api，你只需要保障docker能推送有认证的harbor就可以了。

**Comment by xgy560501** [comment]
请问，构建的入口在哪

**Comment by LianGee** [comment]
> 请问，构建的入口在哪

直接启动就行呀

**Comment by xgy560501** [comment]
就是java项目怎么构建。我看你写了构建的类，但是没有api，具体怎么弄方便指导下？或者您给个微信讨教一下

**Comment by LianGee** [comment]
> 就是java项目怎么构建。我看你写了构建的类，但是没有api，具体怎么弄方便指导下？或者您给个微信讨教一下

代码clone下来，执行类似构建命令mvn install ... 或者 garadle clean package... 
非标准的用shell脚本，执行脚本进行构建。

**Comment by xgy560501** [comment]
额 这个我知道 我是说在这个项目里发起构建的入口api在哪里 我没找到呢
